### ISSUE TITLE
compileTemplate now requires the `id` option.

### ISSUE THREAD

**Issue by zhangchenna** [xinlei3166/vitepress-theme-demoblock#11]
vue提示compileTemplate now requires the `id` option.

**Comment by zhuba-Ahhh** [comment]
加一
```[@vue/compiler-sfc] compileTemplate now requires the `id` option.`.```

![image](https://user-images.githubusercontent.com/84793349/213912276-877629ce-9550-4129-b6bb-5294bb00e98d.png)
