### ISSUE TITLE
v-model:value 在生产环境下报错

### ISSUE THREAD

**Issue by Nakus0426** [xinlei3166/vitepress-theme-demoblock#14]
在::: demo 中使用 `<script setup>` 和 `typescript` 下 `v-model:value` 语法在 dev 模式运行时可正常使用，build 后部署会报错并无法使用。

报错内容
![屏幕截图 2021-12-04 122741](https://user-images.githubusercontent.com/41540888/144697185-dd5bfc91-0a15-4f23-bf0c-ad311d439ef6.png)

在 ::: demo 中的用法
![屏幕截图 2021-12-04 123220](https://user-images.githubusercontent.com/41540888/144697150-33f03cf2-b18c-4653-aeb3-94642c8f1dfe.png)

组件中使用 `emits('update:value',value)` 抛出事件
![屏幕截图 2021-12-04 123311](https://user-images.githubusercontent.com/41540888/144697176-612d1d9f-a9a8-4c8d-b791-fcb00b897eef.png)

**Comment by xinlei3166** [comment]
vue 版本 要在3.2以上，才能正常使用setup模版功能。 如果你的vue版本符合预期，可以提供一个最小demo的github仓库地址，一起排查下错误。

**Comment by Nakus0426** [comment]
> vue 版本 要在3.2以上，才能正常使用setup模版功能；另外尝试下把vitepress、打包工具vite和插件@vitejs/plugin-vue版本升级到与demo中的版本一致。如果你的vue版本符合预期，可以提供一个最小demo的github仓库地址，一起排查下错误。

这是复现的demo
https://github.com/Nakus0426/vitepress-theme-demoblock-issue-demo

**Comment by xinlei3166** [comment]
我已经把项目clone下来了，安装完对应包后 运行正常。建议你去查看下 `node_modules` 中包的版本，或者删除 
 `node_modules` 文件夹，重新安装下包。

![image](https://user-images.githubusercontent.com/22881872/144803617-e00b6312-104f-4db5-b3c6-bf133dc06500.png)

**Comment by Nakus0426** [comment]
> 我已经把项目clone下来了，安装完对应包后 运行正常。建议你去查看下 `node_modules` 中包的版本，或者删除 `node_modules` 文件夹，重新安装下包。
> 
> ![image](https://user-images.githubusercontent.com/22881872/144803617-e00b6312-104f-4db5-b3c6-bf133dc06500.png)

是的，dev模式下正常运行。错误是发生在build部署到nginx后

**Comment by xinlei3166** [comment]
> 

vue 语法错误导致，我已经给你的demo项目提PR了。

**Comment by Nakus0426** [comment]
> > 
> 
> vue 语法错误导致，我已经给你的demo项目提PR了。

想起来了，v-model不能传没有set的计算属性来着。感谢带佬
