### ISSUE TITLE
从1.0.7更新到1.0.7以上版本会报错，1.0.7不会

### ISSUE THREAD

**Issue by SituC** [xinlei3166/vitepress-theme-demoblock#2]
![image](https://user-images.githubusercontent.com/29355875/129912208-0150342c-f952-4cbc-8de1-3e2078d5e5f9.png)

vue版本3.1.1
demo示例代码如下
```
:::demo 使用`left`，`right`来定义`Search`搜索图标位置， 默认`right`

      ```vue
      <template>
        <div>
          <d-search iconPosition="left" style="width: 200px"></d-search>
        </div>
      </template>
      ```
:::

```

d-search已经全局注册

**Comment by xinlei3166** [comment]
升级下版本试一下
"vitepress": "^0.16.1"
"vue": "^3.2.1"

**Comment by SituC** [comment]
> 升级下版本试一下 "vitepress": "^0.16.1"，"vue": "^3.2.1" 。
> 1.0.7版本之后更新了依赖包的版本。

尝试都升级了，还是不行

**Comment by xinlei3166** [comment]
贴个codesanbox链接，或者 github 仓库例子。

**Comment by SituC** [comment]
> 贴个 codesandbox 链接，或者 github 仓库例子。

https://github.com/SituC/vue-devui-temporary.git

现在使用的版本是可以运行的1.0.7的版本，您可以尝试将vitepress-theme-demoblock升级成最新版，会发生报错。
并且vue和vitepress在升级到最新版本的情况下也同样会报错

**Comment by xinlei3166** [comment]
> > 贴个 codesandbox 链接，或者 github 仓库例子。
> 
> https://github.com/SituC/vue-devui-temporary.git
> 
> 现在使用的版本是可以运行的1.0.7的版本，您可以尝试将vitepress-theme-demoblock升级成最新版，会发生报错。
> 并且vue和vitepress在升级到最新版本的情况下也同样会报错

我下载项目运行了，没发现错误。
![image](https://user-images.githubusercontent.com/22881872/130405320-bfbf5fca-c3a9-43ad-9140-8724b8b3d280.png)

**Comment by SituC** [comment]
> > > 贴个 codesandbox 链接，或者 github 仓库例子。
> > 
> > 
> > https://github.com/SituC/vue-devui-temporary.git
> > 现在使用的版本是可以运行的1.0.7的版本，您可以尝试将vitepress-theme-demoblock升级成最新版，会发生报错。
> > 并且vue和vitepress在升级到最新版本的情况下也同样会报错
> 
> 我下载项目运行了，没发现错误。
> ![image](https://user-images.githubusercontent.com/22881872/130405320-bfbf5fca-c3a9-43ad-9140-8724b8b3d280.png)

直接运行的vitepress-theme-demoblock版本是1.0.7的，得更新成最新的应该就会报错了。你是使用的最新版本的吗？

**Comment by xinlei3166** [comment]
是大于1.0.7版本的插件，我给你的demo 项目 发起pr了，你看下。

**Comment by SituC** [comment]
> 是大于1.0.7版本的插件，我给你的demo 项目 发起pr了，你看下。

测试可以的，版本没问题了。但是启动的时候会报可选链的错误，不知道你那会不会有，把?去掉过后就可以正常启动了
![image](https://user-images.githubusercontent.com/29355875/130459628-941070c5-3d70-499f-a70a-8d2b5d66f6e5.png)
直接修改node_modules中的文件后，启动成功
![image](https://user-images.githubusercontent.com/29355875/130459796-d3d83d94-98fa-44e0-af4d-70887451035d.png)
报错有两处，一处是这里`index.js`的`options?.lang` 另一处是`utils.js`中的`options?.scriptImports`

**Comment by xinlei3166** [comment]
> > 是大于1.0.7版本的插件，我给你的demo 项目 发起pr了，你看下。
> 
> 测试可以的，版本没问题了。但是启动的时候会报可选链的错误，不知道你那会不会有，把?去掉过后就可以正常启动了
> ![image](https://user-images.githubusercontent.com/29355875/130459628-941070c5-3d70-499f-a70a-8d2b5d66f6e5.png)
> 直接修改node_modules中的文件后，启动成功
> ![image](https://user-images.githubusercontent.com/29355875/130459796-d3d83d94-98fa-44e0-af4d-70887451035d.png)
> 报错有两处，一处是这里`index.js`的`options?.lang` 另一处是`utils.js`中的`options?.scriptImports`
> 
> 下面的报错是在插件库`yarn docs: dev`过后，同样会报错
> ![image](https://user-images.githubusercontent.com/29355875/130462408-4610f011-205a-4788-b6cd-d4a16cef4e6e.png)

是你的node 版本过低导致的，升级到node 12以上试试。

**Comment by SituC** [comment]
> > > 是大于1.0.7版本的插件，我给你的demo 项目 发起pr了，你看下。
> > 
> > 
> > 测试可以的，版本没问题了。但是启动的时候会报可选链的错误，不知道你那会不会有，把?去掉过后就可以正常启动了
> > ![image](https://user-images.githubusercontent.com/29355875/130459628-941070c5-3d70-499f-a70a-8d2b5d66f6e5.png)
> > 直接修改node_modules中的文件后，启动成功
> > ![image](https://user-images.githubusercontent.com/29355875/130459796-d3d83d94-98fa-44e0-af4d-70887451035d.png)
> > 报错有两处，一处是这里`index.js`的`options?.lang` 另一处是`utils.js`中的`options?.scriptImports`
> > 下面的报错是在插件库`yarn docs: dev`过后，同样会报错
> > ![image](https://user-images.githubusercontent.com/29355875/130462408-4610f011-205a-4788-b6cd-d4a16cef4e6e.png)
> 
> 是你的node 版本过低导致的，升级到node 14 试试。

好的，记忆中家里的node环境是大于14的，不过在公司中测试node14.16.1版本不会报错，非常感谢你的解答
