### ISSUE TITLE
在demoblock中使用setup setup语法糖报错

### ISSUE THREAD

**Issue by gumingWu** [xinlei3166/vitepress-theme-demoblock#21]
![image](https://user-images.githubusercontent.com/24989299/163104927-079a57b4-dfcc-4166-bbdd-148972cfc0a8.png)

在:::demo中，只使用<template>渲染组件没问题，但我想弄个响应式数据绑定到组件，那我就要定义一个ref，所以我需要在script中引入ref：import { ref } from 'vue'，但现在会报错，说我有不期待的{，不知道这个怎么解决
Unexpected "{"
35 |    
36 |      const { defineComponent: _defineComponent } = Vue
37 |  import { ref } from "vue";
   |         ^
38 |  
39 |

```
:::demo 通过 options 修改

(加个文字，不然会渲染成格式块)```vue
<template>
  <w-qrcode :options="options"></w-qrcode>
</template>

<script setup lang="ts">
import { ref } from "vue";

const options = ref({
  color: {
    dark: "#00ff00",
  },
});
</script>
(加个文字，不然会渲染成格式块)```

:::
```

**Comment by xinlei3166** [comment]
vue版本号多少？

**Comment by superchangme** [comment]
牛你牛，其他组件也可以类似这种引入
` md.use(demoBlockPlugin, {
      cssPreprocessor: 'scss',
      scriptImports: ["import * as devuiCommonUtils from '@devui/common'"],
      scriptReplaces: [
        { searchValue: /import ({.*}) from '@devui\/common'/g,
          replaceValue: (s, s1) => `const ${s1} = devuiCommonUtils`
        }
      ]
    })`
