### ISSUE TITLE
style不支持:deep深度选择器

### ISSUE THREAD

**Issue by lch-coder** [xinlei3166/vitepress-theme-demoblock#23]
在md中使用scss以及:deep深度选择器，实际上样式没有渲染，相同的代码到正常的页面是可以渲染的，是不是不支持:deep？

**Comment by xinlei3166** [comment]
插件style这块原理目前是把所有代码中的style合并到一起，然后占用.md文件中style来实现样式展示。:deep目前没有好的方案，可以考虑加不同的className 来完成样式的定义。
