### ISSUE TITLE
Cannot read properties of undefined (reading 'hoistedTags')

### ISSUE THREAD

**Issue by hahaxiaowai** [xinlei3166/vitepress-theme-demoblock#28]
![image](https://user-images.githubusercontent.com/49934348/187031643-8850660b-54f9-4499-96e8-0e5d252e92db.png)

这是因为什么导致的呢

**Comment by zhangaichun123456** [comment]
找到原因了嘛，在mac上我也有这个报错。。。

**Comment by xiaolannuoyi** [comment]
一样的报错，大家怎么解决的呢？

**Comment by yzyerbao** [comment]
vitepress@^1.0.0-alpha.8
这个版本下是正常的，新版本可能是有问题

**Comment by zhangaichun123456** [comment]
> 

我用的是^1.0.0-alpha.4，就是有这个问题，在mac上会出现，window上正常

**Comment by LiZhequ** [comment]
vitepress现在用的是，@mdit-vue/plugin-sfc，sfc相关的内容存在了env.sfcBlocks里，已经没有hoistedTags了，这个库看起来也没人维护了，可以自己修改下

**Comment by xinlei3166** [comment]
2.0版本重写完成，已经适配vitepress@1.0.0-alpha.28。
