### ISSUE TITLE
使用defineCustomElement Api开发自定义组件报错

### ISSUE THREAD

**Issue by zxc125** [xinlei3166/vitepress-theme-demoblock#29]
`
File: D:/*/node_modules/.pnpm/vitepress-theme-demoblock@1.4.2/node_modules/vitepress-theme-demoblock/components/Demo.vue
  91 |  
  92 |      const onClickControl = () => {
  93 |        isExpanded.value = !isExpanded.value
     |                        ^
  94 |        hover.value = isExpanded.value
  95 |      }
`

![image](https://user-images.githubusercontent.com/54338748/187166692-f9d1109d-41c2-47c9-8b7b-51e24f136b1c.png)
![image](https://user-images.githubusercontent.com/54338748/187166717-170b56c6-d4f1-4d0f-b4a1-1726d4b0f5dc.png)
![image](https://user-images.githubusercontent.com/54338748/187166544-aa120b6c-4c5d-4212-be82-f4b22fdbe3c4.png)
![image](https://user-images.githubusercontent.com/54338748/187166637-8dc465d6-8c6a-4b3e-8836-0d4f0fc3fb67.png)

**Comment by xinlei3166** [comment]
可以试下2.0版本，已经支持新版vitepress@1.0.0-alpha.28。

**Comment by xinlei3166** [comment]
自定义组件，我改天试下。

**Comment by xinlei3166** [comment]
2.0版本重写完成，已经适配vitepress@1.0.0-alpha.28。

另外自定义元素我这边测试是可以的，可以参考下 https://github.com/xinlei3166/vitepress-theme-demoblock/blob/main/docs/guide/custom.md

vue自定义元素插槽的用法和vue组件不一致，可以看下 issue   https://github.com/vuejs/core/issues/6142#issuecomment-1311364361
