### ISSUE TITLE
无法解析jsx语法

### ISSUE THREAD

**Issue by haiting** [xinlei3166/vitepress-theme-demoblock#33]
直接在 MD文件里面写 Vue组件，Vue组件如果是带有jsx语法，会无法渲染，如：

`       <template #item="{ element }">
           <a-card  :title="element.name" :extra="<a>More</a>" :style="{ width: 200, height: 150 }">
              Inner Card content
          </a-card>
        </template>
`

`:extra`参数无法渲染

**Comment by haiting** [comment]
创建一个 card.md 文件，代码如下：

:::demo

```vue
<template>
  <a-card  :extra="<a>More</a>"> Inner Card content </a-card>
</template>
```
:::

由于`:extra="<a>More</a>"` 是jsx语法，页面渲染会报错，

报错如下：
[plugin:vite:vue] Transform failed with 1 error:
/Users/bou/working/code/vue-pro/sinogear-frontend-pro-vue/packages/sinogear-frontend-component-vue/docs/src/components/dict-select.md:16:81: ERROR: Unterminated regular expression

**Comment by xinlei3166** [comment]
vue template 里不能使用jsx啊  这代码确定能跑？

**Comment by haiting** [comment]
旧项目的docs用 `markdown-it`，`markdown-it-container` 等配置markdown确实能跑起来

**Comment by haiting** [comment]
创建一个 permission.md 文件，代码如下：

```
<template>
  <a-pagination :total="300"  />
</template>

<script lang="jsx">
export default {
  name: 'SGPagination',
  methods: {
    itemRender({type, originalElement}) {
      if (type === 'prev') {
        return <a>上一页</a>;
      } else if (type === 'next') {
        return <a>下一页</a>;
      }
      return originalElement;
    },
  },
};
</script>

```


函数 `itemRender` 属于 jsx 语法，页面会报错,

报错如下：
[plugin:vite:vue] Transform failed with 1 error:
/docs/src/components/dict-select.md:25:32: ERROR: Unterminated regular expression

**Comment by xinlei3166** [comment]
v3.0.0已支持jsx/tsx，参考：[main/playground/vitepress/guide/index.md](https://github.com/xinlei3166/vitepress-theme-demoblock/blob/main/playground/vitepress/guide/index.md?rgh-link-date=2023-06-26T10%3A09%3A21Z)

`vitepress-theme-demoblock@3.0.0`
`vitepress@1.0.0-beta.3`
`vue@3.3.4`
