### ISSUE TITLE
无法在MD文档  import 第三方库

### ISSUE THREAD

**Issue by haiting** [xinlei3166/vitepress-theme-demoblock#34]
```vue
<template>
  <xl-button>默认按钮</xl-button>
  <xl-button type="primary">主要按钮</xl-button>
  <xl-button type="success">成功按钮</xl-button>
  <xl-button type="info">信息按钮</xl-button>
  <xl-button type="warning">警告按钮</xl-button>
  <xl-button type="danger">危险按钮</xl-button>
</template>

<script>
 import { Button }  from 'ant-design-vue'
 </script>
```
报错：

`[vite] Internal server error: Transform failed with 1 error:
/vitepress-demo/docs/components/button.md:159:11: ERROR: Unexpected "{"
  Plugin: vite:vue
  File: /Users/bou/working/code/vue-pro/vitepress-demo/docs/components/button.md:159:11`

**Comment by xinlei3166** [comment]
markdown 中的vue代码被编译为了 vue 函数组件，需要把 import 转换为 require，可以看下demo element-ui的引入用法。
