### ISSUE TITLE
希望style中也增加替换功能

### ISSUE THREAD

**Issue by lizhen789** [xinlei3166/vitepress-theme-demoblock#36]
在使用过程中需要导入一些组件中的css文件，但无法直接像导入js中那样通过替换来完成。

![image](https://user-images.githubusercontent.com/35031472/203491183-b0e3df33-5150-490e-974b-3b500a3656ae.png)
希望通过替换，把上面注释的替换成下面的真实路径。
就像下面js这样。
![image](https://user-images.githubusercontent.com/35031472/203491327-52d9c4c6-2e49-4ec4-9dd3-f42b08cae845.png)
![image](https://user-images.githubusercontent.com/35031472/203491372-064bc396-308a-4b5c-ad10-f21047551f75.png)

**Comment by xinlei3166** [comment]
v2.0.2 已支持
