### ISSUE TITLE
setup语法糖模式下有报错,普通setup下正常,官方demo线上正常,拉取到本地跟自己搭建的一样错误

### ISSUE THREAD

**Issue by XSLJ** [xinlei3166/vitepress-theme-demoblock#37]
![image](https://user-images.githubusercontent.com/86306773/203902530-a97c81ef-cee7-4da8-b432-498145923b4d.png)

**Comment by YqngQB** [comment]
您好，我也遇到了相同的问题。请问解决了嘛

**Comment by YqngQB** [comment]
> 您好，我也遇到了相同的问题。请问解决了嘛

经过测试 发现与vue版本有关，我将  vue 3.2.45 回退到 vue 3.2.0 后，解决了这个问题

**Comment by xinlei3166** [comment]
2.0.1版本已经锁定vue版本为3.2.44，可以正常使用。

vue3.2.45版本为啥报错，我还没查出来原因，可能是vue的bug。
