### ISSUE TITLE
能否支持移动端demo

### ISSUE THREAD

**Issue by az031120103** [xinlei3166/vitepress-theme-demoblock#38]

**Comment by xinlei3166** [comment]
可以参考下 [varlet-ui](https://github.com/varletjs/varlet/tree/dev/packages/varlet-ui-playground) 移动端框架，它结合了 `@vue/repl` 来展示移动端demo。

移动端的比较简单，可以固定在页面右侧展示一个嵌套的iframe页面，点击文档中的文字或标题，右侧的iframe页面链接同步即可。
