### ISSUE TITLE
setup模式，变量无法绑定到模板上

### ISSUE THREAD

**Issue by yeshaojun** [xinlei3166/vitepress-theme-demoblock#41]
```
<template>
  {{ form.name }}
</template>
<script setup lang="ts">
import { reactive } from 'vue';
const form = reactive({
  name: 'test',
});
</script>
```
报错：form.md:15 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
且：import { reactive } from 'vue';引入方式不支持双引号

**Comment by mengxinssfd** [comment]
vue锁定版本为3.2.44

**Comment by yeshaojun** [comment]
> vue锁定版本为3.2.44

感谢，是我的问题，package.json里面切换了3.2.44，但是node_modules还是3.2.45

**Comment by mengxinssfd** [comment]
> > vue锁定版本为3.2.44
> 
> 感谢，是我的问题，package.json里面切换了3.2.44，但是node_modules还是3.2.45

版本号前面去掉^和~这些符号，只留下版本号，就不会这样了

**Comment by xinlei3166** [comment]
`v3.0.0` 版本已修复这个问题。

`vitepress-theme-demoblock@3.0.0`
`vitepress@1.0.0-beta.3`
`vue@3.3.4`
