### ISSUE TITLE
md文件渲染不支持tsx方式（能否增加一下这个功能）

### ISSUE THREAD

**Issue by wocwin** [xinlei3166/vitepress-theme-demoblock#44]
具体问题如图：
![image](https://user-images.githubusercontent.com/37534478/217188023-e6b5ee64-1da3-411c-af64-afee7955effc.png)

**Comment by yang-xianzhu** [comment]
+1

**Comment by xinlei3166** [comment]
v3.0.0已支持tsx，参考：https://github.com/xinlei3166/vitepress-theme-demoblock/blob/main/playground/vitepress/guide/index.md


`vitepress-theme-demoblock@3.0.0`
`vitepress@1.0.0-beta.3`
`vue@3.3.4`
