### ISSUE TITLE
demo插槽使用的时候报错

### ISSUE THREAD

**Issue by ArealRJ** [xinlei3166/vitepress-theme-demoblock#45]
按照示例去配置了一下，引用的自己的组件，如果不使用demo插槽，不会报错，用了插槽后会报[plugin:vitepress] Cannot read properties of undefined (reading 'sfcBlocks')，http请求也会报一个500，还有一个hashmap 404的错误

**Comment by xinlei3166** [comment]
这个是由于 `vitepress` 版本升级造成的问题。`v3.0.0` 版本插件已变更demo渲染方式，可以试用下。

`vitepress-theme-demoblock@3.0.0`
`vitepress@1.0.0-beta.3`
`vue@3.3.4`
