### ISSUE TITLE
markdown里面不支持引入其他模块吗

### ISSUE THREAD

**Issue by yangzl96** [xinlei3166/vitepress-theme-demoblock#48]
[plugin:vite:vue] Transform failed with 1 error:
/Users/yangzongliu/Downloads/promise-ui-master/docs/components/button/index.md:431:11: ERROR: Unexpected "{"

Unexpected "{"
  429|  }
  430|    
  431|      import { useData } from 'vitepress'
     |             ^
  432|  const { ref } = Vue 

vue 可以引入，其他 模块 无法引入

**Comment by xinlei3166** [comment]
`v3.0.0` 已支持。

`vitepress-theme-demoblock@3.0.0`
`vitepress@1.0.0-beta.3`
`vue@3.3.4`
