### ISSUE TITLE
报错handleErrorFromBinding(ctx)

### ISSUE THREAD

**Issue by nothing-sy** [xinlei3166/vitepress-theme-demoblock#50]
版本信息：
 "vitepress": "1.0.0-alpha.28",
"vitepress-theme-demoblock": "2.0.2",
vue: 3.2.44

报错信息：

node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'D:\projects\new-energy-base\.prettierrc'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at format (file:///D:/projects/new-energy-base/node_modules/.pnpm/vitepress-theme-demoblock@2.0.2_aukpcd4tcdec3kaf6goa6mffd4/node_modules/vitepress-theme-demoblock/dist/bin/help.mjs:9:34)
    at registerComponents (file:///D:/projects/new-energy-base/node_modules/.pnpm/vitepress-theme-demoblock@2.0.2_aukpcd4tcdec3kaf6goa6mffd4/node_modules/vitepress-theme-demoblock/dist/bin/vitepress-register-components.mjs:65:28)
    at file:///D:/projects/new-energy-base/node_modules/.pnpm/vitepress-theme-demoblock@2.0.2_aukpcd4tcdec3kaf6goa6mffd4/node_modules/vitepress-theme-demoblock/dist/bin/vitepress-register-components.mjs:68:1
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\projects\\new-energy-base\\.prettierrc'

看了下 bin/help.mjs文件，里面读取.prettierrc路径使用的是cwd， 所以读取的是我个人项目的根路径， 需要把vitepress-theme-demoblock根目录下的.prettierrc文件拷贝到个人项目根目录才行

**Comment by nothing-sy** [comment]
"vitepress": "1.0.0-alpha.28",
    "vitepress-theme-demoblock": "2.0.2",


> 报错信息：
> 
> node:fs:585 handleErrorFromBinding(ctx); ^
> 
> Error: ENOENT: no such file or directory, open 'D:\projects\new-energy-base.prettierrc' at Object.openSync (node:fs:585:3) at Object.readFileSync (node:fs:453:35) at format (file:///D:/projects/new-energy-base/node_modules/.pnpm/vitepress-theme-demoblock@2.0.2_aukpcd4tcdec3kaf6goa6mffd4/node_modules/vitepress-theme-demoblock/dist/bin/help.mjs:9:34) at registerComponents (file:///D:/projects/new-energy-base/node_modules/.pnpm/vitepress-theme-demoblock@2.0.2_aukpcd4tcdec3kaf6goa6mffd4/node_modules/vitepress-theme-demoblock/dist/bin/vitepress-register-components.mjs:65:28) at file:///D:/projects/new-energy-base/node_modules/.pnpm/vitepress-theme-demoblock@2.0.2_aukpcd4tcdec3kaf6goa6mffd4/node_modules/vitepress-theme-demoblock/dist/bin/vitepress-register-components.mjs:68:1 at ModuleJob.run (node:internal/modules/esm/module_job:197:25) at async Promise.all (index 0) at async ESMLoader.import (node:internal/modules/esm/loader:337:24) { errno: -4058, syscall: 'open', code: 'ENOENT', path: 'D:\projects\new-energy-base\.prettierrc'
> 
> 看了下 bin/help.mjs文件，里面读取.prettierrc路径使用的是cwd， 所以读取的是我个人项目的根路径， 需要把vitepress-theme-demoblock根目录下的.prettierrc文件拷贝到个人项目根目录才行

"vitepress": "1.0.0-alpha.28",
    "vitepress-theme-demoblock": "2.0.2",
vue: 3.2.44

**Comment by xinlei3166** [comment]
`v3.0.0` 已解决这个问题。

`vitepress-theme-demoblock@3.0.0`
`vitepress@1.0.0-beta.3`
`vue@3.3.4`
