### ISSUE TITLE
希望能支持vitepress自带的Badge(向标题添加状态)功能

### ISSUE THREAD

**Issue by haiting** [xinlei3166/vitepress-theme-demoblock#52]
https://vitepress.dev/reference/default-theme-badge#title
<img width="897" alt="image" src="https://github.com/xinlei3166/vitepress-theme-demoblock/assets/20320396/c622b6e7-acf6-4688-a024-dab9158a8776">

目前Badge渲染不出来
<img width="921" alt="image" src="https://github.com/xinlei3166/vitepress-theme-demoblock/assets/20320396/74f36b15-86ca-4add-828b-603d1a0d0219">

**Comment by xinlei3166** [comment]
支持的，调用默认主题方法 `enhanceApp` 。

```js
import DefaultTheme from 'vitepress/theme'
import 'vitepress-theme-demoblock/dist/theme/styles/index.css'
import { useComponents } from './useComponents'

export default {
  ...DefaultTheme,
  enhanceApp(ctx) {
    DefaultTheme.enhanceApp(ctx)
    useComponents(ctx.app)
  }
}
```
