### ISSUE TITLE
大神，版本3.0.1，引入demoblockVitePlugin插件会导致markdown里面的表格失效

### ISSUE THREAD

**Issue by Promise-W** [xinlei3166/vitepress-theme-demoblock#53]
![image](https://github.com/xinlei3166/vitepress-theme-demoblock/assets/7625487/12e2d8fb-86dd-43b1-8d92-e036f24f7ce6)
![image](https://github.com/xinlei3166/vitepress-theme-demoblock/assets/7625487/1f3584a5-b90f-4636-929b-2e47f89f4f2a)

**Comment by Promise-W** [comment]
后发现，表格必须两边补全才能识别
| 参数 | 说明 | 类型 | 默认值 | 必传 |
| -- | -- | -- | -- | -- |
| routes | 路由数组 | Route[] | [] | true |
| fontSize | 字体大小，单位px | number | 14 | false |
| height | 面包屑高度 | number | 36 | false |
| maxWidth | 文本最大显示宽度，超出后显示省略号，单位px | number | 180 | false |
| separator | 分隔符，默认 '' 时为箭头 | string | '' | false |
| target | 如何打开目标URL | '_self' &#124; '_blank' | '_self' | false |

**Comment by xinlei3166** [comment]
这个插件 利用用到了 remark 解析为 语法树，可能是这个原因。
